-- \c documents_database
--
-- create table documents
-- (
--     id         bigserial,
--     title      varchar not null,
--     content    JSON    not null,
--     createdAt timestamptz default now(),
--     updatedAt timestamptz default now(),
--     primary key (id)
-- );
